name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Trigger landing page update
        if: success()
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Triggering landing page update for $VERSION"
          
          # Trigger the ctx-apps repository workflow via repository_dispatch
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.CTX_APPS_TOKEN }}" \
            https://api.github.com/repos/slavakurilyak/ctx-apps/dispatches \
            -d "{\"event_type\":\"ctx-release-published\",\"client_payload\":{\"version\":\"$VERSION\",\"repository\":\"$GITHUB_REPOSITORY\"}}")
          
          http_code=$(echo "$response" | tail -n 1)
          body=$(echo "$response" | head -n -1)
          
          if [ "$http_code" -eq 204 ]; then
            echo "Landing page update triggered successfully"
          else
            echo "Failed to trigger landing page update (HTTP $http_code)"
            echo "Response: $body"
            exit 1
          fi